import type { Campsite } from "@/lib/schemas";

/**
 * Campsite inventory — 25 records across seven Texas regions, deliberately
 * re-authored for real depth (Dataset Depth + Derived Trip Truth +
 * Searchable Attribute Normalization correction, 2026-09-04 — see
 * docs/implementation-decisions.md). This keeps every original id and its
 * general character (region, relative price tier, general "personality" of
 * the site), but every structural field was re-authored, not mechanically
 * copied forward:
 *
 * - `datesAvailable`/`nights`/`distanceMiles` are GONE — those are trip-
 *   derived facts (src/lib/dates.ts, src/lib/geo.ts), never static campsite
 *   properties (see the Campsite type's own doc comment in schemas.ts).
 * - `petFriendly: boolean` -> `petPolicy: {allowed, maxPets}`.
 * - `familyFriendly: boolean` -> `familyFeatures: FamilyFeature[]`.
 * - `nearWater: boolean` -> `waterAccess: {nearby, directAccess, type}`.
 * - `seclusion` stays; a new, DISTINCT `noiseLevel` was added (a secluded
 *   site can still be loud, an unsecluded one can still be quiet).
 * - `amenities` are canonical `AmenityCode`s (src/lib/amenities.ts), not
 *   free-text display strings.
 * - `cancellationPolicy` is a structured `{freeUntilDaysBeforeCheckIn,
 *   latePenaltyNights}`, resolved to display copy relative to the ACTUAL
 *   reservation's check-in date at staging time, never a stale literal date.
 * - `unavailableRanges` gives a few records genuine date-specific
 *   unavailability, so the same site can be available for one requested
 *   date range and not another.
 * - Capacity is rebalanced across 2/4/5/6/8/10-12 (was concentrated at 4).
 *
 * `region` is one of exactly seven named Texas regions, used for
 * deterministic destination-region matching (`matchesDestination` in
 * evaluate.ts, fed a filler-stripped phrase via
 * `normalizeDestinationRegion`). `latitude`/`longitude` are real
 * approximate coordinates for the named town, the ONLY input to any
 * user-relative distance value (src/lib/geo.ts).
 */
export const CAMPSITES: Campsite[] = [
  {
    id: "blue-ridge-14",
    campgroundName: "Blue Ridge Campground",
    siteName: "Site 14",
    siteType: "Tent site",
    description: "A tent site a short walk from the creek.",
    available: true,
    capacity: 4,
    pricePerNight: 142,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: [],
    amenities: ["fire_pit", "picnic_table", "potable_water"],
    waterAccess: { nearby: true, directAccess: false, type: "creek" },
    seclusion: "medium",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 18.5,
    address: "1400 Ranch Rd 12, Wimberley, TX 78676",
    city: "Wimberley",
    state: "TX",
    zip: "78676",
    region: "Hill Country",
    latitude: 29.9974,
    longitude: -98.0958,
  },
  {
    id: "blue-ridge-22",
    campgroundName: "Blue Ridge Campground",
    siteName: "Site 22",
    siteType: "RV site",
    description: "Full-hookup RV pad near the campground entrance.",
    available: true,
    capacity: 6,
    pricePerNight: 165,
    petPolicy: { allowed: false, maxPets: 0 },
    familyFeatures: ["restrooms_nearby"],
    amenities: ["electric_hookup", "dump_station", "restroom"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "low",
    noiseLevel: "high",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 22.0,
    address: "1400 Ranch Rd 12, Wimberley, TX 78676",
    city: "Wimberley",
    state: "TX",
    zip: "78676",
    region: "Hill Country",
    latitude: 29.9974,
    longitude: -98.0958,
  },
  {
    id: "silver-creek-7",
    campgroundName: "Silver Creek Campground",
    siteName: "Site 7",
    siteType: "Cabin",
    description: "A secluded cabin backing onto the river.",
    available: true,
    capacity: 4,
    pricePerNight: 210,
    petPolicy: { allowed: true, maxPets: 1 },
    familyFeatures: [],
    amenities: ["fire_pit", "shower", "wifi"],
    waterAccess: { nearby: true, directAccess: true, type: "river" },
    seclusion: "high",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 14, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 24.5,
    address: "210 River Rd, Concan, TX 78838",
    city: "Concan",
    state: "TX",
    zip: "78838",
    region: "Hill Country",
    latitude: 29.5013,
    longitude: -99.7048,
  },
  {
    id: "cedar-hollow-3",
    campgroundName: "Cedar Hollow Campground",
    siteName: "Site 3",
    siteType: "Tent site",
    description: "A small, private tent site tucked into the trees.",
    available: true,
    capacity: 2,
    pricePerNight: 95,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: [],
    amenities: ["fire_pit", "potable_water"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "high",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 12.0,
    address: "3 Piney Woods Trail, Nacogdoches, TX 75964",
    city: "Nacogdoches",
    state: "TX",
    zip: "75964",
    region: "East Texas",
    latitude: 31.6035,
    longitude: -94.6555,
  },
  {
    id: "pine-ridge-9",
    campgroundName: "Pine Ridge Campground",
    siteName: "Site 9",
    siteType: "Tent site",
    description: "A popular creekside site close to the highway.",
    available: true,
    capacity: 6,
    pricePerNight: 120,
    petPolicy: { allowed: false, maxPets: 0 },
    familyFeatures: ["easy_trails", "restrooms_nearby", "swimming_area"],
    amenities: ["picnic_table", "potable_water", "shower", "restroom"],
    waterAccess: { nearby: true, directAccess: true, type: "creek" },
    seclusion: "low",
    noiseLevel: "high",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 3, latePenaltyNights: 1 },
    unavailableRanges: [{ start: "2026-09-18", end: "2026-09-21" }],
    serviceFee: 15.0,
    address: "9 McKinney Falls Pkwy, Austin, TX 78744",
    city: "Austin",
    state: "TX",
    zip: "78744",
    region: "Austin / Central Texas",
    latitude: 30.1732,
    longitude: -97.7431,
  },
  {
    id: "lakeview-11",
    campgroundName: "Lakeview Campground",
    siteName: "Site 11",
    siteType: "Cabin",
    description: "A busy, family-friendly cabin steps from the lake.",
    available: true,
    capacity: 5,
    pricePerNight: 185,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["swimming_area", "restrooms_nearby"],
    amenities: ["fire_pit", "shower", "boat_launch", "restroom"],
    waterAccess: { nearby: true, directAccess: true, type: "lake" },
    seclusion: "low",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [{ start: "2026-09-05", end: "2026-09-08" }],
    serviceFee: 20.0,
    address: "11 Lake Travis Loop, Austin, TX 78732",
    city: "Austin",
    state: "TX",
    zip: "78732",
    region: "Austin / Central Texas",
    latitude: 30.3936,
    longitude: -97.9269,
  },
  {
    id: "timber-hollow-2",
    campgroundName: "Timber Hollow Campground",
    siteName: "Site 2",
    siteType: "Tent site",
    description: "A remote, wooded tent site well off the main road.",
    available: true,
    capacity: 4,
    pricePerNight: 110,
    petPolicy: { allowed: true, maxPets: 1 },
    familyFeatures: [],
    amenities: ["fire_pit", "potable_water"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "high",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 14.0,
    address: "2 Frio Canyon Rd, Leakey, TX 78873",
    city: "Leakey",
    state: "TX",
    zip: "78873",
    region: "Hill Country",
    latitude: 29.7241,
    longitude: -99.762,
  },
  {
    id: "eagle-point-5",
    campgroundName: "Eagle Point Campground",
    siteName: "Site 5",
    siteType: "RV site",
    description: "A large, amenity-rich RV pad for bigger groups.",
    available: true,
    capacity: 8,
    pricePerNight: 195,
    petPolicy: { allowed: false, maxPets: 0 },
    familyFeatures: ["easy_trails"],
    amenities: ["electric_hookup", "dump_station", "wifi", "shower"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "low",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 28.0,
    address: "5 Government Canyon Rd, San Antonio, TX 78254",
    city: "San Antonio",
    state: "TX",
    zip: "78254",
    region: "San Antonio",
    latitude: 29.5921,
    longitude: -98.7245,
  },
  {
    id: "mossy-creek-4",
    campgroundName: "Mossy Creek Campground",
    siteName: "Site 4",
    siteType: "Tent site",
    description: "A creekside site, an easy walk from parking.",
    available: true,
    capacity: 6,
    pricePerNight: 105,
    petPolicy: { allowed: true, maxPets: 3 },
    familyFeatures: ["restrooms_nearby"],
    amenities: ["fire_pit", "potable_water", "shower", "restroom"],
    waterAccess: { nearby: true, directAccess: false, type: "creek" },
    seclusion: "medium",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 13.0,
    address: "4 Mossy Creek Rd, Bastrop, TX 78602",
    city: "Bastrop",
    state: "TX",
    zip: "78602",
    region: "Austin / Central Texas",
    latitude: 30.1105,
    longitude: -97.3151,
  },
  {
    // Intentionally `available: false` — the one record exercising the
    // static/seasonal-closure availability path, distinct from both
    // `unavailableRanges` (date-specific) and the demo's runtime
    // `unavailableIds` simulated-loss mechanism.
    id: "north-ridge-1",
    campgroundName: "North Ridge Campground",
    siteName: "Site 1",
    siteType: "Cabin",
    description: "A high-end cabin, closed for the season.",
    available: false,
    capacity: 12,
    pricePerNight: 230,
    petPolicy: { allowed: false, maxPets: 0 },
    familyFeatures: [],
    amenities: ["fire_pit", "shower", "wifi", "sauna"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "high",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 14, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 30.0,
    address: "1 Terlingua Ranch Rd, Terlingua, TX 79852",
    city: "Terlingua",
    state: "TX",
    zip: "79852",
    region: "West Texas",
    latitude: 29.3197,
    longitude: -103.6094,
  },
  {
    id: "pedernales-falls-6",
    campgroundName: "Pedernales Falls Campground",
    siteName: "Site 6",
    siteType: "Tent site",
    description: "A family-friendly site near the falls overlook.",
    available: true,
    capacity: 4,
    pricePerNight: 90,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["easy_trails", "restrooms_nearby"],
    amenities: ["fire_pit", "picnic_table", "potable_water", "hiking_trails", "restroom"],
    waterAccess: { nearby: true, directAccess: true, type: "river" },
    seclusion: "medium",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 12.0,
    address: "6 Pedernales Falls Dr, Johnson City, TX 78636",
    city: "Johnson City",
    state: "TX",
    zip: "78636",
    region: "Hill Country",
    latitude: 30.3072,
    longitude: -98.2578,
  },
  {
    id: "guadalupe-river-3",
    campgroundName: "Guadalupe River Campground",
    siteName: "Site 3",
    siteType: "Cabin",
    description: "A riverside cabin popular for tubing trips.",
    available: true,
    capacity: 6,
    pricePerNight: 175,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["swimming_area"],
    amenities: ["tubing_access", "shower", "picnic_table"],
    waterAccess: { nearby: true, directAccess: true, type: "river" },
    seclusion: "low",
    noiseLevel: "high",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 20.0,
    address: "3 River Rd, New Braunfels, TX 78132",
    city: "New Braunfels",
    state: "TX",
    zip: "78132",
    region: "Hill Country",
    latitude: 29.8833,
    longitude: -98.3936,
  },
  {
    id: "enchanted-rock-2",
    campgroundName: "Enchanted Rock Campground",
    siteName: "Site 2",
    siteType: "Tent site",
    description: "A rugged backcountry site below the granite dome.",
    available: true,
    capacity: 2,
    pricePerNight: 100,
    petPolicy: { allowed: true, maxPets: 1 },
    familyFeatures: [],
    amenities: ["fire_pit", "vault_toilet", "stargazing"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "high",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 10.0,
    address: "2 Ranch Rd 965, Fredericksburg, TX 78624",
    city: "Fredericksburg",
    state: "TX",
    zip: "78624",
    region: "Hill Country",
    latitude: 30.5057,
    longitude: -98.8189,
  },
  {
    id: "government-canyon-5",
    campgroundName: "Government Canyon Campground",
    siteName: "Site 5",
    siteType: "Tent site",
    description: "A trailhead-adjacent site good for day-hiking families.",
    available: true,
    capacity: 5,
    pricePerNight: 80,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["easy_trails", "restrooms_nearby"],
    amenities: ["fire_pit", "restroom", "hiking_trails"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "medium",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 3, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 9.0,
    address: "5 Government Canyon Rd, San Antonio, TX 78254",
    city: "San Antonio",
    state: "TX",
    zip: "78254",
    region: "San Antonio",
    latitude: 29.5426,
    longitude: -98.8168,
  },
  {
    id: "medina-lake-8",
    campgroundName: "Medina Lake Campground",
    siteName: "Site 8",
    siteType: "RV site",
    description: "A quiet lakeside RV pad with a private boat launch.",
    available: true,
    capacity: 6,
    pricePerNight: 130,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["swimming_area"],
    amenities: ["boat_launch", "electric_hookup", "shower"],
    waterAccess: { nearby: true, directAccess: true, type: "lake" },
    seclusion: "low",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [{ start: "2026-10-01", end: "2026-10-05" }],
    serviceFee: 18.0,
    address: "8 Medina Lake Dr, Lakehills, TX 78063",
    city: "Lakehills",
    state: "TX",
    zip: "78063",
    region: "San Antonio",
    latitude: 29.5432,
    longitude: -98.9803,
  },
  {
    id: "huntsville-4",
    campgroundName: "Huntsville State Park Campground",
    siteName: "Site 4",
    siteType: "Cabin",
    description: "A quiet, wooded lakeside cabin near the nature center.",
    available: true,
    capacity: 8,
    pricePerNight: 140,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["nature_center", "restrooms_nearby", "easy_trails"],
    amenities: ["fire_pit", "shower", "restroom"],
    waterAccess: { nearby: true, directAccess: false, type: "lake" },
    seclusion: "medium",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 20.0,
    address: "4 Park Rd 40, Huntsville, TX 77340",
    city: "Huntsville",
    state: "TX",
    zip: "77340",
    region: "Houston / Gulf",
    latitude: 30.6188,
    longitude: -95.4747,
  },
  {
    id: "galveston-island-1",
    campgroundName: "Galveston Island Campground",
    siteName: "Site 1",
    siteType: "RV site",
    description: "A busy beachfront RV pad, steps from the sand.",
    available: true,
    capacity: 8,
    pricePerNight: 160,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["swimming_area", "restrooms_nearby", "playground"],
    amenities: ["electric_hookup", "dump_station", "restroom"],
    waterAccess: { nearby: true, directAccess: true, type: "beach" },
    seclusion: "low",
    noiseLevel: "high",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 24.0,
    address: "1 Seawall Blvd, Galveston, TX 77554",
    city: "Galveston",
    state: "TX",
    zip: "77554",
    region: "Houston / Gulf",
    latitude: 29.2144,
    longitude: -94.9227,
  },
  {
    id: "lake-conroe-9",
    campgroundName: "Lake Conroe Campground",
    siteName: "Site 9",
    siteType: "Cabin",
    description: "A quiet cabin overlooking the lake's north shore.",
    available: true,
    capacity: 5,
    pricePerNight: 155,
    petPolicy: { allowed: false, maxPets: 0 },
    familyFeatures: [],
    amenities: ["boat_launch", "wifi", "shower"],
    waterAccess: { nearby: true, directAccess: false, type: "lake" },
    seclusion: "low",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 19.0,
    address: "9 Lake Conroe Dr, Conroe, TX 77304",
    city: "Conroe",
    state: "TX",
    zip: "77304",
    region: "Houston / Gulf",
    latitude: 30.3949,
    longitude: -95.5586,
  },
  {
    id: "possum-kingdom-2",
    campgroundName: "Possum Kingdom Campground",
    siteName: "Site 2",
    siteType: "RV site",
    description: "A quiet bluff-top RV site above the lake.",
    available: true,
    capacity: 6,
    pricePerNight: 145,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: [],
    amenities: ["boat_launch", "electric_hookup"],
    waterAccess: { nearby: true, directAccess: false, type: "lake" },
    seclusion: "medium",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 21.0,
    address: "2 Possum Kingdom Park Rd, Graford, TX 76449",
    city: "Graford",
    state: "TX",
    zip: "76449",
    region: "Dallas / North Texas",
    latitude: 32.8779,
    longitude: -98.4256,
  },
  {
    id: "cedar-hill-6",
    campgroundName: "Cedar Hill Campground",
    siteName: "Site 6",
    siteType: "Tent site",
    description: "A close-in group tent site just south of Dallas.",
    available: true,
    capacity: 10,
    pricePerNight: 85,
    petPolicy: { allowed: true, maxPets: 1 },
    familyFeatures: ["easy_trails", "restrooms_nearby", "playground"],
    amenities: ["fire_pit", "hiking_trails", "restroom"],
    waterAccess: { nearby: true, directAccess: false, type: "lake" },
    seclusion: "low",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 3, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 11.0,
    address: "6 Cedar Hill State Park Rd, Cedar Hill, TX 75104",
    city: "Cedar Hill",
    state: "TX",
    zip: "75104",
    region: "Dallas / North Texas",
    latitude: 32.5885,
    longitude: -96.9561,
  },
  {
    id: "ray-roberts-3",
    campgroundName: "Ray Roberts Lake Campground",
    siteName: "Site 3",
    siteType: "Cabin",
    description: "A modern lakeside cabin north of Denton.",
    available: true,
    capacity: 4,
    pricePerNight: 150,
    petPolicy: { allowed: false, maxPets: 0 },
    familyFeatures: [],
    amenities: ["boat_launch", "shower"],
    waterAccess: { nearby: true, directAccess: true, type: "lake" },
    seclusion: "medium",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 17.0,
    address: "3 Isle du Bois Rd, Pilot Point, TX 76258",
    city: "Pilot Point",
    state: "TX",
    zip: "76258",
    region: "Dallas / North Texas",
    latitude: 33.3699,
    longitude: -97.0058,
  },
  {
    id: "tyler-state-park-7",
    campgroundName: "Tyler State Park Campground",
    siteName: "Site 7",
    siteType: "Tent site",
    description: "A piney, family-friendly site by the fishing pier.",
    available: true,
    capacity: 4,
    pricePerNight: 95,
    petPolicy: { allowed: true, maxPets: 1 },
    familyFeatures: ["restrooms_nearby", "playground"],
    amenities: ["fire_pit", "fishing_pier", "restroom"],
    waterAccess: { nearby: true, directAccess: true, type: "lake" },
    seclusion: "medium",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 12.0,
    address: "7 Park Rd 16, Tyler, TX 75706",
    city: "Tyler",
    state: "TX",
    zip: "75706",
    region: "East Texas",
    latitude: 32.4207,
    longitude: -95.3735,
  },
  {
    id: "caddo-lake-4",
    campgroundName: "Caddo Lake Campground",
    siteName: "Site 4",
    siteType: "Cabin",
    description: "A cypress-shaded cabin deep in the bayou.",
    available: true,
    capacity: 4,
    pricePerNight: 135,
    petPolicy: { allowed: true, maxPets: 1 },
    familyFeatures: [],
    amenities: ["boat_launch", "fire_pit"],
    waterAccess: { nearby: true, directAccess: true, type: "lake" },
    seclusion: "high",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 16.0,
    address: "4 Caddo Lake Rd, Karnack, TX 75661",
    city: "Karnack",
    state: "TX",
    zip: "75661",
    region: "East Texas",
    latitude: 32.6879,
    longitude: -94.1719,
  },
  {
    id: "guadalupe-mountains-1",
    campgroundName: "Guadalupe Mountains Campground",
    siteName: "Site 1",
    siteType: "Tent site",
    description: "A remote, high-desert backcountry tent site.",
    available: true,
    capacity: 4,
    pricePerNight: 60,
    petPolicy: { allowed: false, maxPets: 0 },
    familyFeatures: [],
    amenities: ["vault_toilet", "hiking_trails"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "high",
    noiseLevel: "low",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 8.0,
    address: "1 Guadalupe Pass Rd, Salt Flat, TX 79847",
    city: "Salt Flat",
    state: "TX",
    zip: "79847",
    region: "West Texas",
    latitude: 31.8956,
    longitude: -104.8636,
  },
  {
    id: "palo-duro-canyon-5",
    campgroundName: "Palo Duro Canyon Campground",
    siteName: "Site 5",
    siteType: "RV site",
    description: "A canyon-rim RV site with sweeping views.",
    available: true,
    capacity: 6,
    pricePerNight: 105,
    petPolicy: { allowed: true, maxPets: 2 },
    familyFeatures: ["easy_trails"],
    amenities: ["electric_hookup", "hiking_trails", "shower"],
    waterAccess: { nearby: false, directAccess: false, type: "none" },
    seclusion: "medium",
    noiseLevel: "medium",
    cancellationPolicy: { freeUntilDaysBeforeCheckIn: 7, latePenaltyNights: 1 },
    unavailableRanges: [],
    serviceFee: 15.0,
    address: "5 Park Rd 5, Canyon, TX 79015",
    city: "Canyon",
    state: "TX",
    zip: "79015",
    region: "West Texas",
    latitude: 34.9483,
    longitude: -101.6685,
  },
];
