import type { TripIntent } from "@/lib/schemas";

/**
 * Recommendation-readiness gate (Search Truth correction, 2026-09-02 — see
 * docs/implementation-decisions.md). This is the THIRD gate the standing
 * rules require, deliberately distinct from the other two and never
 * collapsed into either:
 *
 *   1. Semantic understanding — IntentInterpretation.status
 *      ("Does the model understand the request?")
 *   2. Deterministic prerequisites — checkSearchPrerequisites /
 *      checkBookingDatePrerequisites (src/lib/prerequisites.ts)
 *      ("Does the application have the facts an action objectively needs?")
 *   3. Recommendation readiness — THIS module
 *      ("Even once 1 and 2 are satisfied, is there enough structured intent
 *      that a specific ranked recommendation is not effectively random?")
 *
 * Reproduced failure this fixes: "Find me somewhere good for camping" ->
 * CampOps asked for dates, the user supplied them, and CampOps immediately
 * recommended a specific campsite (Mossy Creek) with no other basis for the
 * pick at all. Dates alone answer "when", never "where" or "what kind of
 * trip" — a recommendation built from dates alone is not explainable as
 * fitting the user, it's just whatever sorts first.
 *
 * Deliberately NOT a confidence score: this is a plain count of which
 * distinguishing dimensions are structurally present, each one an
 * objectively checkable fact about TripIntent, not a probabilistic
 * judgment. The PRD's own acceptable dimensions — area/destination, party
 * size, or an important preference/trip character — are treated as
 * interchangeable: any ONE of them is enough to make a recommendation
 * explainable, and the system does not require all three.
 *
 * Exploratory Discovery correction (2026-09-07 — see
 * docs/implementation-decisions.md): the rule above is the correct one for
 * an AVAILABILITY-BACKED search, but it let a purely exploratory browse
 * ("What are some quiet campgrounds that are good for families?") slip
 * straight through to a specific, geographically arbitrary recommendation
 * — "quiet"/"family-friendly" alone satisfied `hasTripCharacter`, so no
 * destination was ever required, even though the request names no place at
 * all. For exploratory discovery specifically, a destination signal
 * (`destinationRegion` or `originZip`) is REQUIRED — other trip-character
 * preferences do not substitute for it, because a geographically unscoped
 * "here's A quiet, family-friendly site" isn't a meaningfully narrowed
 * answer to a browsing question. This does not apply to the
 * availability-backed path, whose own interchangeable-dimensions rule is
 * unchanged from the original Search Truth correction.
 */

export type RecommendationReadinessResult =
  | { status: "ready" }
  | {
      status: "insufficient";
      question: string;
      /** Deterministic quick replies for the exploratory destination ask
       * (Exploratory Discovery correction, 2026-09-07) — generated by the
       * application itself, not the model, so the multi-step branch
       * follow-up ("A specific park/region" -> "Which park or region?")
       * works every time, never dependent on the model choosing to offer
       * it. Absent for the general (availability-backed) question, which
       * has no natural short answer set. */
      quickReplies?: { label: string; followUpQuestion: string | null }[];
    };

function hasAnyRequirementSignal(intent: TripIntent): boolean {
  return (
    intent.hardRequirements.length > 0 ||
    intent.flexibleConstraints.length > 0 ||
    intent.preferences.length > 0 ||
    intent.priorities.length > 0
  );
}

const GENERAL_READINESS_QUESTION =
  "To recommend a specific site, tell me a bit more — a region you have in mind, how many people are coming, or what matters most for the trip (quiet, pet-friendly, family-friendly, and so on).";

const EXPLORATORY_DESTINATION_QUESTION =
  "What area or destination should I search in for campgrounds?";

/**
 * `availabilityBacked` mirrors the same classification `checkSearchPrerequisites`
 * already uses (`isExploratoryDiscoveryMessage`, threaded through from
 * page.tsx) — the two gates must agree on which mode a request is in, never
 * independently re-derive it.
 */
export function checkRecommendationReadiness(
  intent: TripIntent,
  options: { availabilityBacked: boolean },
): RecommendationReadinessResult {
  const hasDestination = !!intent.destinationRegion || !!intent.originZip;

  if (!options.availabilityBacked) {
    if (hasDestination) return { status: "ready" };
    return {
      status: "insufficient",
      question: EXPLORATORY_DESTINATION_QUESTION,
      quickReplies: [
        { label: "A specific park/region", followUpQuestion: "Which park or region?" },
      ],
    };
  }

  const hasPartySize = intent.guestCount !== null;
  const hasTripCharacter = hasAnyRequirementSignal(intent);

  if (hasDestination || hasPartySize || hasTripCharacter) {
    return { status: "ready" };
  }
  return { status: "insufficient", question: GENERAL_READINESS_QUESTION };
}
